### ISSUE TITLE
Changing timing of the prone command

### ISSUE THREAD

**Issue by Colonel-Suave** [kaydol/CrouchProner#1]
I have need of this program and it works nicely. However, 1 second is too long of a hold time for me, personally. How do I change the hold time to something else, say 350 or 450 ms?

I attempted this on my own by opening the CrouchProner.cpp app and changing the first HOLD_TIME = 900 to 400. That did not work and anything else is unfortunately beyond my ability...

**Comment by kaydol** [comment]
Hello. Thanks for letting me know someone is actually using this program. I didn't expect it to go beyond the original person it was made for. 

As for the timings, you can write a .bat that starts CrouchProner with any hold time you like. Just put it next to your CrouchProner.exe before launching the .bat. You can find the .bat file that starts the program with HOLD_TIME=400 ms here: 

https://github.com/kaydol/CrouchProner/tree/master/Release

**Comment by Colonel-Suave** [comment]
No problem, on a console controller, usually the crouch/prone button is the same and is controlled in this way in any FPS- one press for crouch, one to revert to stand, hold to prone. In Rainbow 6: Siege, there is no option for this on Mouse/Keyboard controllers and this feature is actually heavily requested on related forums. I'm surprised you haven't heard more questions about it as this program has turned maneuvering from a chore to a breeze. Thanks again for this!
